name: votex
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  camera: ^0.11.1
  crypto: ^3.0.6
  face_camera: ^0.1.4
  firebase_analytics: ^11.4.2
  firebase_core: ^3.11.0
  firebase_remote_config: ^5.4.0
  flutter:
    sdk: flutter
  google_mlkit_face_detection: ^0.12.0
  http: ^1.3.0
  http_parser: ^4.1.2
  mime: ^2.0.0
  path_provider: ^2.1.5
  pinput: ^5.0.1
  provider: ^6.1.2
  qr_code_scanner_plus: ^2.0.9+1
  shared_preferences: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
