// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE3e25H2jb4HnVhK1F-I9YEI0o1kS0P9w',
    appId: '1:870931856466:web:44139d874b83ade478f38b',
    messagingSenderId: '870931856466',
    projectId: 'votex-6ce21',
    authDomain: 'votex-6ce21.firebaseapp.com',
    storageBucket: 'votex-6ce21.firebasestorage.app',
    measurementId: 'G-ZCQN9EKFVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA50PT_-ZfsBW1KJ7AgQgKTvzJMXZkXIrc',
    appId: '1:870931856466:android:97af3cfce69d1a2a78f38b',
    messagingSenderId: '870931856466',
    projectId: 'votex-6ce21',
    storageBucket: 'votex-6ce21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7abgjswQpXmgn1M93V5FIKwF6_XkcArc',
    appId: '1:870931856466:ios:e26cccc797721e6b78f38b',
    messagingSenderId: '870931856466',
    projectId: 'votex-6ce21',
    storageBucket: 'votex-6ce21.firebasestorage.app',
    iosBundleId: 'com.example.votex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7abgjswQpXmgn1M93V5FIKwF6_XkcArc',
    appId: '1:870931856466:ios:e26cccc797721e6b78f38b',
    messagingSenderId: '870931856466',
    projectId: 'votex-6ce21',
    storageBucket: 'votex-6ce21.firebasestorage.app',
    iosBundleId: 'com.example.votex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAE3e25H2jb4HnVhK1F-I9YEI0o1kS0P9w',
    appId: '1:870931856466:web:52c03cba4a79010d78f38b',
    messagingSenderId: '870931856466',
    projectId: 'votex-6ce21',
    authDomain: 'votex-6ce21.firebaseapp.com',
    storageBucket: 'votex-6ce21.firebasestorage.app',
    measurementId: 'G-MLR3DSCK7D',
  );
}

